import type { CategoryIconId } from "@/config/category-icons";
import {
  AirplaneIcon,
  ArrowDownIcon,
  ArrowUpIcon,
  BasketIcon,
  BicycleIcon,
  BirthdayCakeIcon,
  BitcoinIcon,
  BoltIcon,
  BriefcaseIcon,
  BuildingIcon,
  BusIcon,
  CalendarBlankIcon,
  CameraIcon,
  CarIcon,
  CartIcon,
  ChartUptrendIcon,
  CoinsIcon,
  CreditCardIcon,
  CurrencyCircleDollarIcon,
  DotsThreeIcon,
  DropIcon,
  DumbbellIcon,
  FamilyIcon,
  FilmIcon,
  ForkKnifeIcon,
  FuelPumpIcon,
  GameControllerIcon,
  GiftIcon,
  GlobeIcon,
  GraduationCapIcon,
  HeartIcon,
  HouseIcon,
  LaptopIcon,
  LeafIcon,
  MusicNoteIcon,
  NotebookIcon,
  PaintbrushIcon,
  PartyPopperIcon,
  PawPrintIcon,
  PercentIcon,
  PillsIcon,
  ReceiptIcon,
  ScissorsIcon,
  ShieldIcon,
  ShippingBoxIcon,
  ShoppingBagIcon,
  SmartphoneIcon,
  SofaIcon,
  SparkleIcon,
  StarIcon,
  StorefrontIcon,
  TagIcon,
  TakeoutBagIcon,
  TicketIcon,
  TrainIcon,
  TrophyIcon,
  TshirtIcon,
  TvIcon,
  WalletIcon,
  WifiIcon,
  WineGlassIcon,
  WrenchIcon,
  type Icon,
} from "@/lib/icons";

/** Maps every pickable category icon id to its SF Symbol component. */
export const CATEGORY_ICON_COMPONENTS: Record<CategoryIconId, Icon> = {
  wallet: WalletIcon,
  coins: CoinsIcon,
  banknote: CurrencyCircleDollarIcon,
  "credit-card": CreditCardIcon,
  receipt: ReceiptIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-up": ArrowUpIcon,
  "chart-up": ChartUptrendIcon,
  bitcoin: BitcoinIcon,
  percent: PercentIcon,
  briefcase: BriefcaseIcon,
  building: BuildingIcon,
  "fork-knife": ForkKnifeIcon,
  takeout: TakeoutBagIcon,
  wine: WineGlassIcon,
  cake: BirthdayCakeIcon,
  basket: BasketIcon,
  car: CarIcon,
  bus: BusIcon,
  train: TrainIcon,
  bicycle: BicycleIcon,
  fuel: FuelPumpIcon,
  airplane: AirplaneIcon,
  "shopping-bag": ShoppingBagIcon,
  cart: CartIcon,
  storefront: StorefrontIcon,
  tag: TagIcon,
  "shipping-box": ShippingBoxIcon,
  tshirt: TshirtIcon,
  scissors: ScissorsIcon,
  house: HouseIcon,
  sofa: SofaIcon,
  bolt: BoltIcon,
  drop: DropIcon,
  wifi: WifiIcon,
  smartphone: SmartphoneIcon,
  laptop: LaptopIcon,
  wrench: WrenchIcon,
  heart: HeartIcon,
  pills: PillsIcon,
  dumbbell: DumbbellIcon,
  "graduation-cap": GraduationCapIcon,
  book: NotebookIcon,
  "paw-print": PawPrintIcon,
  family: FamilyIcon,
  gift: GiftIcon,
  sparkle: SparkleIcon,
  paintbrush: PaintbrushIcon,
  camera: CameraIcon,
  "music-note": MusicNoteIcon,
  "game-controller": GameControllerIcon,
  "party-popper": PartyPopperIcon,
  film: FilmIcon,
  tv: TvIcon,
  ticket: TicketIcon,
  trophy: TrophyIcon,
  globe: GlobeIcon,
  leaf: LeafIcon,
  star: StarIcon,
  shield: ShieldIcon,
  calendar: CalendarBlankIcon,
  "dots-three": DotsThreeIcon,
};
